export const APP_CONSTANTS = {
  DEFAULT_PAGE_SIZE: 10,
  PAGE_SIZE_OPTIONS: [10, 20, 50, 100],
  DATE_FILTER_OPTIONS: [
    { label: 'Today', value: 'today' },
    { label: 'Last 7 days', value: '7d' },
    { label: 'Last 30 days', value: '30d' },
    { label: 'Last 90 days', value: '90d' },
    { label: 'This year', value: 'year' },
  ],
  STATUS_TONE_MAP: {
    Approved: 'success',
    Active: 'success',
    Delivered: 'success',
    Completed: 'success',
    Captured: 'success',
    'In Stock': 'success',
    Processing: 'warning',
    'Under review': 'warning',
    Pending: 'warning',
    'Low Stock': 'warning',
    'Ready to process': 'warning',
    Shipped: 'info',
    Confirmed: 'info',
    Suspended: 'danger',
    Rejected: 'danger',
    Failed: 'danger',
    Cancelled: 'danger',
    'Out of Stock': 'danger',
    Refunded: 'neutral',
    Draft: 'neutral',
    Inactive: 'neutral',
  } as Record<string, 'success' | 'warning' | 'info' | 'neutral' | 'danger'>,
}
